### ISSUE TITLE
코드리뷰 시 참고부탁

### ISSUE THREAD

**Issue by hyuneu-n** [nowjiin/livfit-be#35]
1. 스웨거 모든 ApiResponse 삭제

2. 스웨거 description에 test_dev 테스트 토큰을 accessToken으로 바꿔놨다가 몇번 새로고침하니까 토큰이 안 먹어서 다시 리프레시 토큰으로 설정해두었습니다.

3. 운동 종료 시 자동으로 포인트(300p) 지급 기능 추가
![image](https://github.com/user-attachments/assets/f0e6368e-9bd2-43bd-983e-d1f2823b669d)
![image](https://github.com/user-attachments/assets/38bdf487-dabe-4a67-b6bc-b13a381fad89)

4. 메인뱃지 설정 기능 추가
- 같은 뱃지를 중복으로 소유하고있으면 오류가 나기때문에 데베에서 임의로 test_badge, test_badge2, test_badge3 남기고 다 삭제했습니다.
뱃지 아이디로 메인뱃지 설정되는 것 200 확인 완료.. 정도?

5. 지금 point 엔티티와 와이어프레임을 비교해보면
![image](https://github.com/user-attachments/assets/eecfae11-c938-47f9-94bb-a339c31e5cf2)
밑 작은 글씨에 넣을 column이 존재하지 않는데, 미션 혹은 챌린지 명을 크게 표시해준다면 저 작은 글씨에는 어떤 정보를 넣는게 좋을지 아니면 없애면 좋을지 한번 여쭤봅니당

6. 다음 저의 할 일 -> 마이페이지 : 챌린지, 거북목 등의 개발이 확실하게 끝난 이후에 진행하도록 하겠습니다 ~

**Comment by nowjiin** [comment]
일단 확인했고
dev에서 main으로 PR이 날라온 시점에서 코드 리뷰하겠음 !
